# rclone repository example. Configure the `backup-remote` remote with rclone.

[repository]
repository = "rclone:backup-remote:rustic"

[backup]
git-ignore = true
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]

[[backup.snapshots]]
sources = ["/home"]

[forget]
keep-daily = 7
keep-weekly = 4
keep-monthly = 12
keep-yearly = 5
