# rustic config file to use s3 storage
# Note that this internally uses opendal S3 service, see https://opendal.apache.org/docs/rust/opendal/services/struct.S3.html
# where endpoint, bucket and root are extracted from the repository URL.
[repository]
repository = "opendal:s3"
password = "password"

# Other options can be given here - note that opendal also support reading config from env files or AWS config dirs, see the opendal S3 docu
[repository.options]
access_key_id = "xxx"
secret_access_key = "xxx"
bucket = "bucket_name"
endpoint = "https://s3.amazonaws.com"
region = "auto" # Explicit region is better, else requests are delayed to determine correct region.
root = "/path/to/repo"
