[repository]
repository = "opendal:s3"
password = "password"

[repository.options]
root = "/"
bucket = "bucket_name"
endpoint = "https://p7v1.ldn.idrivee2-40.com"
region = "gb-ldn"
access_key_id = "xxx"
secret_access_key = "xxx"
