# rustic config file to use sftp storage
# Note:
# - currently sftp only works on unix
# - Using sftp with password is not supported yet, use key authentication, e.g. use
#   ssh-copy-id user@host
[repository]
repository = "opendal:sftp"
password = "mypassword"

[repository.options]
user = "myuser"
endpoint = "host:port"
root = "path/to/repo"
