[package]
name = "rustic_testing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aho-corasick = { workspace = true }
once_cell = { workspace = true }
tempfile = { workspace = true }
