[advisories]
ignore = [
  # FIXME!: See https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643.
  # There is no workaround available yet.
  "RUSTSEC-2023-0071",
  # FIXME: `Instant` is still being used by deny. We need to wait for a new version.
  "RUSTSEC-2024-0384",
]
