# Local repository example. This follows the output style of `rustic setup`.

[repository]
repository = "/backup/rustic"
no-cache = true

[backup]
git-ignore = true
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
globs = ["!**/target/**", "!**/node_modules/**"]

[[backup.snapshots]]
sources = ["/home"]

[forget]
keep-daily = 7
keep-weekly = 4
keep-monthly = 12
keep-yearly = 5
