# rustic config file to use opendal storage - in this case b2
[repository]
repository = "opendal:b2" # just specify the opendal service here
password = "mypassword"

# all other options are given here.
# Please refer to https://opendal.apache.org/docs/rust/opendal/services/index.html for the options supported by each service
[repository.options]
# Here, we give the required b2 options, see https://opendal.apache.org/docs/rust/opendal/services/struct.B2.html
root = "repo-path" # Set the work directory for backend
key_id = "my_id" # B2 application key keyID
application_key = ".my_key" # B2 application key applicationKey
bucket = "bucket_name" # B2 bucket name
bucket_id = "bucket_id" # B2 bucket_id
