on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    if: ${{ github.repository_owner == 'rustic-rs' }}
    name: Label issue
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          # check if issue doesn't have any labels
          if [[ $(gh issue view $ISSUE_URL --json labels -q '.labels | length') -eq 0 ]]; then
            # add S-triage label
            gh issue edit $ISSUE_URL --add-label "S-triage"
          fi
